# Generated by Django 5.1.4 on 2024-12-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tictactoespot',
            table='spot',
        ),
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('instanced_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.instancedentity')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
