# Generated by Django 5.1.4 on 2024-12-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_tictactoespot_table_tictactoegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='spot1_in_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_spot1', to='server.tictactoespot'),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='spot2_in_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_spot2', to='server.tictactoespot'),
        ),
    ]
